const stages = [
  {key:'Customer',title:'Capturing the\nCustomer Need',description:'Hearing the customer request, constraints and success criteria before any specification is written.',check:['Request','Users','Constraints','Success','Priority'],agent:'CUSTOMER',task:'Customer request',input:'Idea or brief',output:'Confirmed customer need',right:'Clarifying the request with the customer',progress:'Capturing the customer need',card1:['Customer Brief','NOVA · Customer request','Goals · Users · Constraints','Need confirmed with the customer'],card2:['Success Criteria','Primary outcome','Must-have scope','Out of scope'],maturity:'Request',agents:['Customer']},
  {key:'Business Developer',title:'Writing the\nSpecification',description:'Turning the customer need into a clear specification, acceptance criteria and scope the team can build.',check:['Scope','Stories','Acceptance','Rules','Review'],agent:'BUSINESS DEVELOPER',task:'Product specification',input:'Customer need',output:'Approved specification',right:'Writing stories and acceptance criteria',progress:'Drafting the specification',card1:['Specification','NOVA · Product spec','Stories · Rules · Acceptance','Specification in review'],card2:['Acceptance Criteria','Account rules','Core scenarios','Edge cases'],maturity:'Spec',agents:['Business Developer','Requirements Editor']},
  {key:'Architect',title:'Shaping the\nSystem',description:'Defining services, data and API contracts that the specification can be built on.',check:['System Map','Data Model','API Contracts','Integrations','Review'],agent:'SOLUTION ARCHITECT',task:'Architecture and API contracts',input:'Approved specification',output:'System architecture',right:'Mapping services, data and APIs',progress:'Defining the architecture',card1:['Services','NOVA · System map','App → API → Services','Data model and auth defined'],card2:['Integrations','Identity service','Data storage','External APIs'],maturity:'Architecture',agents:['Solution Architect']},
  {key:'UI/UX Designer',title:'Designing the\nExperience',description:'Turning the specification into user flows, wireframes and a visual interface the developers can build.',check:['User Flow','Wireframes','Visual System','Screens','Review'],agent:'UI/UX DESIGNER',task:'Flows and interface',input:'Specification + architecture',output:'Approved UI/UX',right:'Designing flows and the interface',progress:'Designing the experience',card1:['Experience','NOVA · Flows and screens','Journey · Wireframes · UI','Primary path designed'],card2:['Interface','Core screens','Components','Interaction states'],maturity:'Design',agents:['UX Designer','UI Designer']},
  {key:'Project Manager',title:'Planning the\nBuild',description:'Sequencing the work, owners and dependencies so design and engineering can proceed together.',check:['Plan','Owners','Dependencies','Milestones','Risks'],agent:'PROJECT MANAGER',task:'Delivery plan',input:'Spec, architecture and design',output:'Build plan',right:'Sequencing work and owners',progress:'Planning the build',card1:['Plan','NOVA · Delivery plan','Milestones · Owners · Risks','Build sequence agreed'],card2:['Workstreams','Design handoff','Backend','Frontend'],maturity:'Plan',agents:['Project Manager']},
  {key:'Backend Developer',title:'Building the\nServices',description:'Implementing APIs, data and business rules behind the approved design.',check:['API','Data','Business Rules','Auth','Review'],agent:'BACKEND DEVELOPER',task:'Services and APIs',input:'Architecture + plan',output:'Working backend',right:'Implementing APIs and data',progress:'Building backend services',card1:['APIs','NOVA · Service build','Auth · Data · Rules','Core endpoints in progress'],card2:['Services','Identity','Core domain','Integrations'],maturity:'Backend',agents:['Backend Developer','API Engineer']},
  {key:'Frontend Developer',title:'Building the\nInterface',description:'Implementing the approved screens and connecting them to the backend.',check:['App Shell','Screens','API Wiring','States','Review'],agent:'FRONTEND DEVELOPER',task:'Screens and client integration',input:'UI/UX + APIs',output:'Working frontend',right:'Building screens against the APIs',progress:'Building the interface',card1:['Screens','NOVA · Client build','Shell · Screens · States','UI connected to APIs'],card2:['Integration','Authentication','Core screens','Error states'],maturity:'Frontend',agents:['Frontend Developer']},
  {key:'Deployment Engineer',title:'Preparing the\nRelease',description:'Packaging the build, configuring the environment and preparing the deployment.',check:['Build','Config','Environment','Health','Handoff'],agent:'DEPLOYMENT ENGINEER',task:'Release package',input:'Frontend + backend',output:'Deployable build',right:'Packaging the build for release',progress:'Preparing deployment',card1:['Release','NOVA · Deployable build','Config · Environment · Health','Package ready for checks'],card2:['Environment','Build artifact','Runtime config','Health checks'],maturity:'Release',agents:['Deployment Engineer']},
  {key:'QA Engineer',title:'Testing the\nProduct',description:'Running functional, regression and acceptance tests and sending defects back to the builders.',check:['Functional','Regression','Acceptance','Defects','Retest'],agent:'QA ENGINEER',task:'Test pass',input:'Deployable build',output:'QA report',right:'Testing the running product',progress:'Running the test pass',card1:['Test Report','NOVA · QA pass','Cases · Defects · Retests','Quality pass in progress'],card2:['Coverage','Functional cases','Regression','Open defects'],maturity:'QA',agents:['QA Engineer','Test Analyst']},
  {key:'Smoke Tester',title:'Running the\nSmoke Pass',description:'Checking the critical path on the deployed build before the integration pass.',check:['Startup','Sign-in','Core Path','Critical APIs','Sign-off'],agent:'SMOKE TESTER',task:'Smoke sign-off',input:'QA-tested build',output:'Smoke result',right:'Checking the critical path',progress:'Running smoke tests',card1:['Smoke Result','NOVA · Critical path','Startup · Sign-in · Core flow','Smoke pass in progress'],card2:['Critical Checks','Application starts','Sign-in works','Core task completes'],maturity:'Smoke',agents:['Smoke Tester']},
  {key:'Integration Pass',title:'Closing the\nIntegration Pass',description:'Confirming frontend, backend and deployment work together and handing over the integrated product.',check:['End to End','Contracts','Environment','Handover','Complete'],agent:'INTEGRATION LEAD',task:'Integration complete',input:'Smoke-approved build',output:'Integrated product',right:'Confirming the full path works together',progress:'Closing the integration pass',card1:['Integration','NOVA · Integrated build','UI · API · Deployment','Handover package'],card2:['Handover','Contracts verified','Environment healthy','Product handed over'],maturity:'Integrated',agents:['Integration Lead','Release Checker']},
];

const images = ['01_Customer_HighRes.png','02_Spec_Writer_HighRes.png','03_Architect_HighRes.png','04_UI_UX_Designer_HighRes.png','05_Project_Manager_HighRes.png','06_Backend_Developer_HighRes.png','07_Frontend_Developer_HighRes.png','08_Deployment_Engineer_HighRes.png','09_QA_Engineer_HighRes.png','10_Smoke_Tester_HighRes.png','11_Integration_Pass_HighRes.png'];
const icons = ['93b19','24054','801bf','01271','41a03','fee84','d0f92','cab2f','0c7c4','d0f92','cab2f'];

export const stagesExport = stages.map((stage, index) => ({
  ...stage,
  image: `/assets/stages/${images[index]}`,
  icon: `/assets/${icons[index]}.svg`,
}));

export { stagesExport as stages };

export const examples = {
  'An online store': 'Build an online store where customers can browse products, save favourites, place orders and track deliveries. Include account sign-in and an admin dashboard.',
  'A customer portal': 'Build a customer portal with secure sign-in, project updates, shared documents and a support request system.',
  'An internal business tool': 'Build an internal workspace where our team can manage projects, assign tasks, track progress and share documents.',
};
