const stages = [
  {key:'Customer',title:'Capturing the\nCustomer Need',description:'Hearing the customer request, constraints and success criteria before any specification is written.',check:['Request','Users','Constraints','Success','Priority'],agent:'CUSTOMER',task:'Customer request',input:'Idea or brief',output:'Confirmed customer need',right:'Clarifying the request with the customer',progress:'Capturing the customer need',card1:['Customer Brief','NOVA · Customer request','Goals · Users · Constraints','Need confirmed with the customer'],card2:['Success Criteria','Primary outcome','Must-have scope','Out of scope'],maturity:'Request',agents:['Customer']},
  {key:'Spec Writer',title:'Writing the\nSpecification',description:'Turning the customer need into a clear specification, acceptance criteria and scope the team can build.',check:['Scope','Stories','Acceptance','Rules','Review'],agent:'SPEC WRITER',task:'Product specification',input:'Customer need',output:'Approved specification',right:'Writing stories and acceptance criteria',progress:'Drafting the specification',card1:['Specification','NOVA · Product spec','Stories · Rules · Acceptance','Specification in review'],card2:['Acceptance Criteria','Account rules','Core scenarios','Edge cases'],maturity:'Spec',agents:['Spec Writer','Requirements Editor']},
  {key:'Architect',title:'Shaping the\nSystem',description:'Defining services, data and API contracts that the specification can be built on.',check:['System Map','Data Model','API Contracts','Integrations','Review'],agent:'SOLUTION ARCHITECT',task:'Architecture and API contracts',input:'Approved specification',output:'Technical specification',right:'Mapping services, data and APIs',progress:'Defining the architecture',card1:['Technical Spec','NOVA · System map','App → API → Services','Data model and auth defined'],card2:['Integrations','Identity service','Data storage','External APIs'],maturity:'Architecture',agents:['Solution Architect']},
  {key:'PM',title:'Reviewing the\nEstimate',description:'Taking the architecture to the customer, agreeing the estimate, then handing the plan to UI/UX.',check:['Estimate','Customer Review','Feedback','Plan','Handoff'],agent:'PROJECT MANAGER',task:'Estimate and customer review',input:'Technical specification',output:'Customer-approved plan',right:'Reviewing the estimate with the customer',progress:'Reviewing the estimate',card1:['Estimate','NOVA · Customer review','Scope · Cost · Sequence','Waiting on the customer'],card2:['Plan','Customer feedback','UI/UX handoff','Build sequence'],maturity:'Estimate',agents:['Project Manager']},
  {key:'UI/UX',title:'Designing the\nExperience',description:'Turning the approved plan into user flows, wireframes and a visual interface.',check:['User Flow','Wireframes','Visual System','Screens','Review'],agent:'UI/UX DESIGNER',task:'Flows and interface',input:'Customer-approved plan',output:'Approved UI/UX',right:'Designing flows and the interface',progress:'Designing the experience',card1:['Experience','NOVA · Flows and screens','Journey · Wireframes · UI','Primary path designed'],card2:['Interface','Core screens','Components','Interaction states'],maturity:'Design',agents:['UX Designer','UI Designer']},
  {key:'Frontend',title:'Building the\nInterface',description:'Implementing the approved screens while the backend is built alongside.',check:['App Shell','Screens','API Wiring','States','Review'],agent:'FRONTEND DEVELOPER',task:'Screens and client integration',input:'Approved UI/UX',output:'Working frontend',right:'Building screens against the APIs',progress:'Building the interface',card1:['Screens','NOVA · Client build','Shell · Screens · States','UI connected to APIs'],card2:['Integration','Authentication','Core screens','Error states'],maturity:'Frontend',agents:['Frontend Developer']},
  {key:'Backend',title:'Building the\nServices',description:'Implementing APIs, data and business rules while the frontend is built alongside.',check:['API','Data','Business Rules','Auth','Review'],agent:'BACKEND DEVELOPER',task:'Services and APIs',input:'Technical specification',output:'Working backend',right:'Implementing APIs and data',progress:'Building backend services',card1:['APIs','NOVA · Service build','Auth · Data · Rules','Core endpoints in progress'],card2:['Services','Identity','Core domain','Integrations'],maturity:'Backend',agents:['Backend Developer','API Engineer']},
  {key:'QA',title:'Testing the\nProduct',description:'Testing the build and sending fixes back to frontend and backend before they return.',check:['Functional','Frontend Fixes','Backend Fixes','Retest','Sign-off'],agent:'QA ENGINEER',task:'Test pass',input:'Frontend and backend',output:'QA report',right:'Testing and sending fixes back',progress:'Running the test pass',card1:['Test Report','NOVA · QA pass','Cases · Fixes · Retests','Fixes are back with the builders'],card2:['Fixes','Frontend tasks','Backend tasks','Retest'],maturity:'QA',agents:['QA Engineer','Test Analyst']},
  {key:'Deployment Engineer',title:'Preparing the\nRelease',description:'Packaging the build, configuring the environment and preparing the deployment.',check:['Build','Config','Environment','Health','Handoff'],agent:'DEPLOYMENT ENGINEER',task:'Release package',input:'QA-approved build',output:'Deployable build',right:'Packaging the build for release',progress:'Preparing deployment',card1:['Release','NOVA · Deployable build','Config · Environment · Health','Package ready for the final review'],card2:['Environment','Build artifact','Runtime config','Health checks'],maturity:'Release',agents:['Deployment Engineer']},
  {key:'Smoke Tester',title:'Reviewing the\nFinal App',description:'Opening the finished application for the final review.',check:['Startup','Sign-in','Core Path','Critical APIs','Sign-off'],agent:'SMOKE TESTER',task:'Final app review',input:'Deployed build',output:'Approved application',right:'Preparing the final application',progress:'Preparing the final app',card1:['Final App','NOVA · Ready to review','Startup · Sign-in · Core flow','Waiting for the final review'],card2:['Review','Application starts','Sign-in works','Core task completes'],maturity:'Final',agents:['Smoke Tester']},
];

const images = ['01_Customer_HighRes.png','02_Spec_Writer_HighRes.png','03_Architect_HighRes.png','05_Project_Manager_HighRes.png','04_UI_UX_Designer_HighRes.png','07_Frontend_Developer_HighRes.png','06_Backend_Developer_HighRes.png','09_QA_Engineer_HighRes.png','08_Deployment_Engineer_HighRes.png','10_Smoke_Tester_HighRes.png'];
const icons = ['93b19','24054','801bf','41a03','01271','d0f92','fee84','0c7c4','cab2f','d0f92'];

export const stagesExport = stages.map((stage, index) => ({
  ...stage,
  image: `/assets/stages/${images[index]}`,
  icon: `/assets/${icons[index]}.svg`,
}));

export { stagesExport as stages };

export const examples = {
  'An online store': 'Build an online store where customers can browse products, save favourites, place orders and track deliveries. Include account sign-in and an admin dashboard.',
  'A customer portal': 'Build a customer portal with secure sign-in, project updates, shared documents and a support request system.',
  'An internal business tool': 'Build an internal workspace where our team can manage projects, assign tasks, track progress and share documents.',
};
