import React,{useState} from 'react';
export function MobileFrame({children,previewUrl}) {
  return <div className="phone"><div className="phone-screen"><div className="device-status"><b>9:41</b><span className="notch"/><span>••• ▰</span></div><div className="app-viewport" data-testid="app-viewport">{previewUrl ? <iframe title="Built application" src={previewUrl} sandbox="allow-scripts allow-forms"/> : children}</div><div className="home-indicator"/></div></div>;
}
const Bar=({width='100%',height=8})=><span className="skeleton" style={{width,height}}/>;
const Box=({children,className=''})=><div className={`skeleton-box ${className}`}>{children}</div>;
export function StageSkeleton({stage,progress}) {
 const visual=[0,1,4,7,3,5,5,6,8,7][stage]??7;
 return <div className={`mobile-content skeleton-stage stage-${stage}`} key={stage} aria-label={`Stage ${stage+1} application preview loading`} aria-busy="true"><div className="mobile-brand">NOVA <span>N</span></div>
 {visual===0 ? <><Box><Bar width="60%" height={12}/><Bar/><Bar width="85%"/><Bar width="40%" height={22}/></Box><div className="mobile-grid">{[0,1].map(i=><Box key={i}><Bar width={26} height={26}/><Bar/><Bar width="65%"/></Box>)}</div><Box><Bar width="55%"/><Bar/><Bar width="80%"/></Box></> :
 visual===1 ? <><h4>Application structure</h4><small>4 modules · 18 user stories</small>{['Entry & identity','Core experience','Detail & activity','Profile & preferences'].map((x,i)=><Box key={x} className="structure-row"><span>{i+1}</span><div><b>{x}</b><Bar width={`${90-i*10}%`}/></div></Box>)}</> :
 visual===2 ? <><Box className="wireframe"><small>YOUR WORKSPACE</small><Bar width="75%" height={15}/><Bar/><Bar width="45%" height={24}/></Box><div className="mobile-grid"><Box className="wireframe"><Bar height={42}/></Box><Box className="wireframe"><Bar height={42}/></Box></div><h4>Recent activity</h4><Box className="wireframe"><Bar/><Bar width="65%"/></Box></> :
 visual===3 ? <><div className="swatches"><i/><i/><i/><i/></div><Box className="design-hero"><small>YOUR WORKSPACE</small><b>Everything, in one place.</b><Bar width="70%"/><Bar width="50%" height={22}/></Box><div className="mobile-grid"><Box><Bar height={36}/><Bar/></Box><Box><Bar height={36}/><Bar/></Box></div><Bar width="65%"/></> :
 visual===4 ? <><h4>Connecting your application</h4><div className="architecture-nodes"><Box>App shell<Bar/></Box><span>↓</span><Box>API services<Bar width="70%"/></Box><span>↓</span><div className="mobile-grid"><Box>Identity<Bar/></Box><Box>Data<Bar/></Box></div></div></> :
 visual===5 ? <><Box className="design-hero"><b>Everything, in one place.</b><Bar/><Bar width="45%" height={24}/></Box><div className="mobile-grid"><Box><Bar height={40}/></Box><Box><Bar height={40}/></Box></div><h4>Connecting modules</h4>{['Authentication','Core experience','API integration'].map((x,i)=><div className="build-row" key={x}><span>{progress>(i+1)*25?'✓':'◌'}</span>{x}<Bar width={35}/></div>)}</> :
 visual===6 ? <><Box><Bar width="70%" height={14}/><Bar height={60}/></Box><h4>Quality checks</h4>{['Functional tests','Accessibility','Performance','Regression'].map((x,i)=><div className="build-row" key={x}><span>{progress>i*25?'✓':'◌'}</span>{x}<Bar width={30}/></div>)}<div className="test-scan"/></> :
 visual===7 ? <><Box className="design-hero"><b>Release candidate</b><Bar height={35}/></Box><h4>Acceptance review</h4>{['Business goals','User journeys','Release readiness'].map(x=><Box key={x} className="acceptance">✓ {x}<Bar width="75%"/></Box>)}</> :
 <><div className="release-loader">↑</div><h4>Preparing your release</h4><Box><Bar width="70%"/><Bar/><Bar width="55%"/></Box><div className="mobile-grid"><Box><Bar height={35}/></Box><Box><Bar height={35}/></Box></div></>}
 <div className="mobile-bottom">{['Home','Explore','Saved','Profile'].map(x=><span key={x}><Bar width={16} height={10}/>{x}</span>)}</div></div>;
}
export function ReadyApp(){
 const [tab,setTab]=useState('Home'),[items,setItems]=useState(['Project overview','Shared collection']),[saved,setSaved]=useState([]),[draft,setDraft]=useState(''),[adding,setAdding]=useState(false);
 return <div className="mobile-content ready-app"><div className="mobile-brand">NOVA <span>N</span></div>{tab==='Profile'?<><div className="profile-avatar">N</div><h3>Your workspace</h3><p>Demo member</p><div className="skeleton-box">Personal workspace<br/><small>Version 1.0.0 · Ready</small></div></>:<><div className="ready-hero"><small>YOUR WORKSPACE</small><h3>Everything, in one place.</h3><p>Pick up where you left off.</p><button onClick={()=>setAdding(true)}>+ Create new</button></div><div className="mobile-grid"><button className="tile" onClick={()=>setTab('Explore')}>▣<b>My items</b><small>{items.length} items</small></button><button className="tile" onClick={()=>setTab('Saved')}>◇<b>Saved</b><small>{saved.length} items</small></button></div>{adding&&<form className="add-item" onSubmit={e=>{e.preventDefault();if(draft.trim()){setItems([...items,draft.trim()]);setDraft('');setAdding(false);}}}><label htmlFor="new-item">Item name</label><input id="new-item" value={draft} onChange={e=>setDraft(e.target.value)} maxLength={60} autoFocus/><button type="submit">Add item</button><button type="button" onClick={()=>setAdding(false)}>Cancel</button></form>}<h4>{tab==='Saved'?'Saved items':tab==='Explore'?'Your items':'Recent activity'}</h4>{(tab==='Saved'?saved:items).length===0&&<p>No saved items yet. Tap a star to save one.</p>}{(tab==='Saved'?saved:items).map((x,i)=><div className="nova-item" key={i}><span>▤</span><div><b>{x}</b><small>Updated just now</small></div><button aria-label={`${saved.includes(x)?'Unsave':'Save'} ${x}`} onClick={()=>setSaved(saved.includes(x)?saved.filter(v=>v!==x):[...saved,x])}>{saved.includes(x)?'★':'☆'}</button></div>)}</>}<nav className="mobile-bottom" aria-label="NOVA navigation">{['Home','Explore','Saved','Profile'].map(x=><button key={x} aria-current={tab===x?'page':undefined} onClick={()=>setTab(x)}>{x}</button>)}</nav></div>;
}
